name: ising_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - black=19.10b0
  - jupyter=1.0.0
  - lmfit=1.0.0
  - matplotlib=3.1.3
  - numpy=1.18.5
  - pandas=1.0.3
  - pingouin=0.3.4
  - pip=20.0.2
  - python=3.8.3
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=47.1.1
  - statsmodels=0.11.1
  - sympy=1.5.1
