name: ising_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asteval=0.9.16
  - attrs=19.3.0
  - brotlipy=0.7.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - decorator=4.4.2
  - defusedxml=0.6.0
  - idna=2.9
  - importlib_metadata=1.6.0
  - ipython=7.13.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - joblib=0.15.1
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libgfortran-ng=7.5.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - littleutils=0.2.2
  - lmfit=1.0.0
  - more-itertools=8.3.0
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - notebook=6.0.3
  - numpy=1.18.5
  - outdated=0.2.0
  - pandas-flavor=0.2.0
  - pathspec=0.7.0
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pingouin=0.3.4
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - py=1.8.1
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python-dateutil=2.8.1
  - python_abi=3.8
  - qtpy=1.9.0
  - requests=2.23.0
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - statsmodels=0.11.1
  - sympy=1.5.1
  - tabulate=0.8.7
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - uncertainties=3.1.2
  - urllib3=1.25.9
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xarray=0.15.1
  - zipp=3.1.0
  - appdirs=1.4.3
  - astroid=2.4.1
  - backcall=0.1.0
  - black=19.10b0
  - bleach=3.1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - click=7.1.2
  - cycler=0.10.0
  - dbus=1.13.14
  - entrypoints=0.3
  - expat=2.2.6
  - fastcache=1.1.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=1.6.0
  - ipykernel=5.1.4
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jupyter=1.0.0
  - jupyter_console=6.1.0
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pip=20.0.2
  - ptyprocess=0.6.0
  - pylint=2.5.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pytest=5.4.2
  - python=3.8.3
  - pytz=2020.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - readline=8.0
  - regex=2020.5.14
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.4
  - typed-ast=1.4.1
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zeromq=4.3.1
  - zlib=1.2.11
